##
# Multi-stage build:
# 1) Build custom scrcpy websocket server (apk) and ship as scrcpy-server.jar
# 2) Build ws-scrcpy dist bundle
# 3) Runtime image with adb + node server
#
# 第一阶段用 Debian + apt 安装 OpenJDK 17，只拉 debian 基础镜像（国内加速对 debian 支持较好）；
# 若仍超时，请用「离线导入基础镜像」见 Docker镜像加速.md
##

FROM debian:bookworm-slim AS scrcpy-server-builder

ARG ANDROID_SDK_ROOT=/opt/android-sdk
ARG ANDROID_PLATFORM=android-33
ARG ANDROID_BUILD_TOOLS=33.0.2

ENV ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT}
ENV PATH=${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools

RUN apt-get update \
  && apt-get install -y --no-install-recommends openjdk-17-jdk-headless curl unzip ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Install Android commandline tools + required packages for Gradle Android plugin
RUN mkdir -p "${ANDROID_SDK_ROOT}/cmdline-tools" \
  && curl -L -o /tmp/cmdline-tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" \
  && unzip -q /tmp/cmdline-tools.zip -d "${ANDROID_SDK_ROOT}/cmdline-tools" \
  && mv "${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools" "${ANDROID_SDK_ROOT}/cmdline-tools/latest" \
  && rm -f /tmp/cmdline-tools.zip

RUN yes | sdkmanager --licenses >/dev/null \
  && sdkmanager "platform-tools" "platforms;${ANDROID_PLATFORM}" "build-tools;${ANDROID_BUILD_TOOLS}" >/dev/null

WORKDIR /work
COPY _scrcpy_fork/ ./_scrcpy_fork/
RUN chmod +x _scrcpy_fork/gradlew

WORKDIR /work/_scrcpy_fork
RUN ./gradlew :server:assembleRelease --no-daemon

# Copy release apk to a stable path; ws-scrcpy expects scrcpy-server.jar
RUN cp -f server/build/outputs/apk/release/server-release.apk /work/scrcpy-server.jar


FROM node:20-bookworm AS ws-builder

WORKDIR /work

# Ensure native deps build (node-pty)
RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
ENV PUPPETEER_SKIP_DOWNLOAD=1
RUN npm ci

COPY . .

# Replace vendor jar with our custom build
COPY --from=scrcpy-server-builder /work/scrcpy-server.jar ./vendor/Genymobile/scrcpy/scrcpy-server.jar

RUN npm run dist


FROM node:20-bookworm-slim AS runtime

WORKDIR /app

# adb from Android SDK (Debian may not have android-sdk-platform-tools)
ENV PATH="${PATH}:/opt/android-sdk/platform-tools"
COPY --from=scrcpy-server-builder /opt/android-sdk/platform-tools /opt/android-sdk/platform-tools

# Dist contains its own package.json for runtime (generated by webpack plugin)
COPY --from=ws-builder /work/dist/ ./dist/

ENV NODE_ENV=production
ENV WS_SCRCPY_CONFIG=/app/config.yaml

EXPOSE 8000

WORKDIR /app/dist
CMD ["npm","start"]

